import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button } from "@chakra-ui/react"
import { ArrowForwardIcon } from '@chakra-ui/icons'
import { Input } from "@chakra-ui/react"
import Script from 'next/script'
import React from 'react'

export default function Home() {
  function registerUser(event){
    event.preventDefault() // don't redirect the page
 
    /*fetch("https://throw-me-to.vercel.app/api/create", {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: {
        name: event.target.name.value,
        url: event.target.url.value
      },
    })*/



var url = "https://throw-me-to.vercel.app/api/create";

var xhr = new XMLHttpRequest();
xhr.open("POST", url);

xhr.setRequestHeader("Content-Type", "application/json");

xhr.onreadystatechange = function () {
   if (xhr.readyState === 4) {
      console.log(xhr.status);
      console.log(xhr.responseText);
   }};

var data = `{
  "name": "rtestva",
  "url": "ytestaa"
}
`;

xhr.send(data);




    alert(0)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ThrowMeTo- A hassle free url shortner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/jQuery.js" />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Throw-Me-To
          <div style={{ fontSize: '1rem' }}>
            ( it&apos;s a url shortner )
          </div>
        </h1>
        <p className={styles.description}>
          don&apos;t worry we&apos;ll throw you well.
        </p>
        <form onSubmit={registerUser}>
          
        <div className={styles.input_cont}>
          <Input placeholder="my url name" style={{ width: '200px' }} required id="url" name="url" type="text" />
          <Input placeholder="enter your looong url" id="name" name="name" type="text" required/>
        </div>
        <div className={styles.button_doiIt}>
          <Button id="button" type="submit" colorScheme="teal" rightIcon={<ArrowForwardIcon />} style={{ margin: "5px" }}>
            Do It!
          </Button>
        </div>

        </form>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          (c) volcareso
        </span>
      </footer>
    </div>
  )
}
