import React from 'react'
import fetch from 'node-fetch'
import { useRouter } from 'next/router'
import router from 'next/router'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { Button } from "@chakra-ui/react"
import { ArrowForwardIcon } from '@chakra-ui/icons'
import { Input } from "@chakra-ui/react"
import Script from 'next/script'
import React from 'react'

export default function To() {
    const router = useRouter()
    let todo = {
        name: router.query.q
    };

    fetch('/api/get/', {
        method: 'POST',
        body: JSON.stringify(todo),
        headers: { 'Content-Type': 'application/json' }
    }).then(res => res.json())
        .then(json => window.location.replace(json.url))

    return (<>
<div className={styles.container}>
      <Head>
        <title>ThrowMeTo- A hassle free url shortner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/jQuery.js" />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Please wait for ~5 seconds...
          <div style={{ fontSize: '1rem' }}>
             Chill.
          </div>
        </h1>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          (c) volcareso
        </span>
      </footer>
    </div>
    </>)
}
